#!/usr/bin/env node
/**
 * PreToolUse guard: refuse the write, rather than explain the rule afterwards.
 *
 * A skill advises and an agent may ignore it; a hook decides. Everything here
 * is already enforced by `npm run quality`, so the hook adds no new rule — it
 * moves the same rejection from merge time to keystroke time, which is the
 * difference between a comment on a pull request and a defect that never
 * existed.
 *
 * The rules are imported from scripts/check-patterns.mjs rather than restated.
 * A second copy would drift, and the version that drifts is always the one that
 * lets the bad write through.
 *
 * Reads the PreToolUse payload on stdin, prints a permission decision on
 * stdout. Silent on allow.
 */
import { existsSync } from 'node:fs'
import { relative, isAbsolute, normalize } from 'node:path'
import { RULES, blankBlockComments } from '../check-patterns.mjs'

const IGNORE_DIRECTIVE = 'check-patterns-ignore-next-line'

const read = (stream) =>
  new Promise((resolve) => {
    let data = ''
    stream.setEncoding('utf8')
    stream.on('data', (chunk) => (data += chunk))
    stream.on('end', () => resolve(data))
  })

function deny(reason) {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: reason,
      },
    }),
  )
  process.exit(0)
}

/** The text this call would introduce: whole file for Write, replacement for Edit. */
function incomingText(tool, input) {
  if (tool === 'Write') return input.content ?? ''
  return [input.new_string, ...(input.edits ?? []).map((e) => e.new_string)]
    .filter(Boolean)
    .join('\n')
}

/**
 * Normalised, so `./src/x.ts` and `src/sub/../x.ts` are both `src/x.ts`. Every
 * check below is a path prefix test, and an un-normalised path walks straight
 * past all of them while still landing in the guarded directory.
 */
function repoRelative(filePath) {
  if (!filePath) return ''
  return normalize(isAbsolute(filePath) ? relative(process.cwd(), filePath) : filePath)
}

// `.spec.` as well as `.test.`, matching the checker's SPECS glob. A narrower
// regex here means `it.only` in e2e/smoke.spec.ts sails past the hook and is
// caught only by CI — and P-23, the pitfall the skipped-test rule exists for,
// was an end-to-end suite. The guard has to agree with the checker or it teaches
// people that the hook is the lenient one.
const isSpec = (file) => /\.(?:test|spec)\.[cm]?[jt]sx?$/.test(file)
const isProduct = (file) => file.startsWith('src/') && /\.(ts|tsx|css)$/.test(file)

async function main() {
  let payload
  try {
    payload = JSON.parse((await read(process.stdin)) || '{}')
  } catch {
    process.exit(0) // Never block on a payload we cannot read.
  }

  const tool = payload.tool_name
  if (tool !== 'Write' && tool !== 'Edit') process.exit(0)

  const input = payload.tool_input ?? {}
  const file = repoRelative(input.file_path)
  if (!file || file.startsWith('..')) process.exit(0)

  // shadcn primitives are generated by the CLI. Hand-editing one is how a
  // design system stops being a system: the next `shadcn add` overwrites it,
  // or worse, does not and the two drift apart silently. Its render test is
  // the opposite case — the CLI never writes one, and the whole point of
  // requiring one (canonical-examples.md) is that someone hand-writes it.
  if (file.startsWith('src/components/ui/') && !isSpec(file)) {
    deny(
      `${file} is a shadcn primitive. Add or update it with the shadcn CLI, then restyle through ` +
        `the semantic tokens — hand-written files here are overwritten or, worse, quietly diverge.`,
    )
  }

  // TDD in the domain layer, enforced rather than encouraged. Pure functions
  // with a spec that already exists have no excuse for test-after.
  if (tool === 'Write' && /^src\/domain\/[^/]+\.ts$/.test(file) && !isSpec(file)) {
    const spec = file.replace(/\.ts$/, '.test.ts')
    if (!existsSync(spec)) {
      deny(
        `${spec} does not exist. src/domain/ is written test-first: the failing test comes before ` +
          `the implementation. Write ${spec}, watch it fail, then write ${file}.`,
      )
    }
  }

  // A rule whose violation is the path, not a line — there is nothing to scan
  // for, and scanning would be the wrong question anyway: a perfectly written
  // component stylesheet is still a component stylesheet. This is where the
  // hook earns the most, since the file it refuses is one nobody has to
  // remember to delete later.
  const forbidden = RULES.find((rule) => rule.forbidsExistence?.(file) && !rule.exempt?.(file))
  if (forbidden) deny(`${forbidden.id}: ${file}\n\n${forbidden.message}`)

  const text = incomingText(tool, input)
  if (!text) process.exit(0)

  const applicable = RULES.filter((rule) =>
    rule.pattern === undefined
      ? false
      : rule.id === 'no-skipped-tests'
        ? isSpec(file)
        : isProduct(file) && !rule.exempt?.(file),
  )

  // Same blanking the checker does, for the same reason and so the two agree:
  // a doc comment is where these patterns get explained, and a guard that
  // rejects the explanation while CI accepts it is a guard people route around.
  const lines = blankBlockComments(text).split('\n')

  for (const rule of applicable) {
    lines.forEach((line, index) => {
      // Skips the next line only. A `break` here would let one directive
      // silence the rule for the whole rest of the write.
      if (index > 0 && lines[index - 1].includes(IGNORE_DIRECTIVE)) return

      const match = rule.pattern.exec(line)
      rule.pattern.lastIndex = 0
      if (match) deny(`${rule.id}: ${match[0]}\n\n${rule.message}`)
    })
  }

  process.exit(0)
}

main()
